/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pivotal' at '5/4/16 12:43 PM' with Gradle 1.12
 *
 * @author pivotal, @date 5/4/16 12:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
